// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXzKdLJc-DaWWI3nYv4cOqyuOYFtLI4hk',
    appId: '1:267175626212:web:ec1eaaef28e05e7af133f1',
    messagingSenderId: '267175626212',
    projectId: 'daily-water-count',
    authDomain: 'daily-water-count.firebaseapp.com',
    storageBucket: 'daily-water-count.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfuNqB2rwv0fCRHC8ixmJaLpHt2_I3kG4',
    appId: '1:267175626212:android:be663ab28ac70c7ff133f1',
    messagingSenderId: '267175626212',
    projectId: 'daily-water-count',
    storageBucket: 'daily-water-count.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAK4qSlpMkq9UUWaIYN1vpZhkeecqndXUY',
    appId: '1:267175626212:ios:acb83047432fb86ff133f1',
    messagingSenderId: '267175626212',
    projectId: 'daily-water-count',
    storageBucket: 'daily-water-count.appspot.com',
    iosClientId: '267175626212-bloqors3qf4f6dhrr9r516rjfh5sg033.apps.googleusercontent.com',
    iosBundleId: 'com.example.waterCountApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAK4qSlpMkq9UUWaIYN1vpZhkeecqndXUY',
    appId: '1:267175626212:ios:acb83047432fb86ff133f1',
    messagingSenderId: '267175626212',
    projectId: 'daily-water-count',
    storageBucket: 'daily-water-count.appspot.com',
    iosClientId: '267175626212-bloqors3qf4f6dhrr9r516rjfh5sg033.apps.googleusercontent.com',
    iosBundleId: 'com.example.waterCountApp',
  );
}
